Added logic to detect and set unicode emoji in the custom status slas…
brightscout-alpha/mattermost-server pull request #13
Opened 2021-04-08 13:10 UTC by manojosh

…h command

#### Summary

#### Ticket Link

#### Release Note

```release-note
```

2021-04-21 11:13 UTC, chetanyakan requested changes

2021-04-21 11:13 UTC, chetanyakan commented on app/slashcommands/command_custom_status.go
> +		emojiString := spaceSeparatedMessage[0]
Use `strings.Fields()` instead
Ref: https://golang.org/pkg/strings/#Fields

2021-04-21 11:13 UTC, chetanyakan commented on app/slashcommands/command_custom_status.go
> +			textString := strings.Join(spaceSeparatedMessage[1:], " ")
Make sure to test this with just the emoji and no message

2021-04-26 08:43 UTC, manojmalik20 commented
Corresponding PR to mattermost master is already made.
https://github.com/mattermost/mattermost-server/pull/17475

2021-04-26 08:43 UTC, closed without merging